name: Create a branch with updated man pages and application translations

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: linkchecker/linkchecker
          ref: master
          # Needed for hatch-vcs to extract LinkChecker version from tag
          # https://github.com/actions/checkout/issues/249
          fetch-depth: 0

      - name: Install Ubuntu packages
        run: sudo apt install gettext git

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python packages
        run: >
            pip3 install dnspython beautifulsoup4 requests \
                         hatchling hatch-vcs sphinx sphinx_epytext \
                         sphinx_rtd_theme sphinx-sitemap sphinx-intl

      - name: Prepare git environment
        run: |
            git config user.email "linkchecker@linkchecker.github.io"
            git config user.name "LinkChecker"
            git checkout -b man-updates
            git remote add local ${{ github.server_url }}/${{ github.repository }}

      - name: Build man pages
        run: |
            python3 -m hatchling build -t sdist --hooks-only
            make -C doc locale
            git commit -a -m "Update doc translation catalogs"
            make -C doc man
            git commit -a -m "Update man pages"

      - name: Build application translations catalogs
        run: |
            rm -f po/linkchecker.pot
            make -C po
            git commit -a -m "Update application translation catalogs"

      - name: Push changes
        run: >
            git push --set-upstream local man-updates
